# Generated by Django 5.1.5 on 2025-01-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_prestador', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_franqueado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_pagamento', to='servicos.solicitacaoservico')),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoFranqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100)),
                ('franqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
