# Generated by Django 5.1.5 on 2025-02-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0005_alter_prestador_cpf'),
        ('servicos', '0002_alter_servico_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamação',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastramento.prestador'),
        ),
    ]
