# Generated by Django 5.1.5 on 2025-01-21 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnpj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=14, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cnpj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CNPJ',
                'verbose_name_plural': 'CNPJs',
            },
        ),
        migrations.CreateModel(
            name='Cpf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cpf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPF',
                'verbose_name_plural': 'CPFs',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=35)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('bairro', models.CharField(max_length=80)),
                ('rua', models.CharField(max_length=80)),
                ('num', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_enderecos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('idade', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
                ('cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastramento.cpf')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastramento.email')),
                ('endereco', models.ManyToManyField(to='cadastramento.endereco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=20)),
                ('razao_social', models.CharField(blank=True, max_length=80, null=True)),
                ('ie', models.CharField(blank=True, max_length=50, null=True)),
                ('cnpj', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastramento.cnpj')),
                ('cpf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastramento.cpf')),
                ('email', models.ManyToManyField(to='cadastramento.email')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastramento.endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
            },
        ),
        migrations.CreateModel(
            name='Franqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('clientes', models.ManyToManyField(to='cadastramento.cliente')),
                ('endereco', models.ManyToManyField(to='cadastramento.endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='franqueado', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ManyToManyField(to='cadastramento.prestador')),
            ],
            options={
                'verbose_name': 'Franqueado',
                'verbose_name_plural': 'Franqueados',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.AddField(
            model_name='prestador',
            name='servico',
            field=models.ManyToManyField(to='cadastramento.servico'),
        ),
    ]
