# Generated by Django 5.1.5 on 2025-02-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
