# Generated by Django 5.1.5 on 2025-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0003_alter_prestador_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='idade',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
