# Generated by Django 5.1.5 on 2025-02-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0004_alter_prestador_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='cpf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastramento.cpf'),
        ),
    ]
