# Generated by Django 5.1.5 on 2025-01-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_solicitada', models.DateField()),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('negada', 'Negada'), ('finalizada', 'Finalizada')], default='pendente', max_length=20)),
                ('foto_cliente', models.ImageField(blank=True, null=True, upload_to='ordens/fotos_clientes/')),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('reclamacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_cliente', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_prestador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('alerta_1dia', models.BooleanField(default=False)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prestadores.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('foto_anexo', models.ImageField(blank=True, null=True, upload_to='recados/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestadores.ordemservico')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ordens', models.IntegerField(default=0)),
                ('total_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
