# Generated by Django 5.1.5 on 2025-02-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastramento', '0002_userprofile'),
        ('prestadores', '0002_prestador_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastramento.prestador'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='cadastramento.prestador'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_prestador', to='cadastramento.prestador'),
        ),
        migrations.AlterField(
            model_name='recado',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recados', to='cadastramento.prestador'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='cadastramento.prestador'),
        ),
        migrations.DeleteModel(
            name='Prestador',
        ),
    ]
